"""
AGENTIC ZERO - AGENTIC SHIELD
Policy Engine v1.0

Role:
  The Machine observes, learns and prescribes - but nobody decides what
  happens to a prescription until now. policy_engine.py is the core
  arbitration module: for every prescription generated by prescriptor.py,
  it issues one of four verdicts:

    APPROVE   - matches an explicitly autonomous-allowed action, high
                confidence, low/medium severity. Can apply without a human.
    SANDBOX   - matches an approval-required action, or unknown action
                type. Can be staged/tested but not activated live without
                sign-off.
    ESCALATE  - matches an always-human action, low confidence, or
                CRITICAL severity. Goes straight to a human.
    REJECT    - explicitly contradicts a governance rule (e.g. would
                bypass a regulated/compliance boundary). Never applied.

  Decision basis (in order of precedence):
    1. organism-level autonomy_design (always_human / approval_required /
       autonomous_actions) from siop_internal.json, if the prescription
       names an affected organism we have a profile for - most specific,
       wins over global rules.
    2. swarm-level shield_arbitration (always_human / approval_required /
       autonomous_allowed) from swarm_coordination_<process>.json -
       process-wide default when no organism-specific signal applies.
    3. confidence / severity thresholds - safety net when no textual
       match exists at all (default-safe: SANDBOX, never silent APPROVE).

  This module never auto-applies anything by itself; it only classifies.
  Activation of an APPROVE verdict is a separate, later concern
  (approval_engine.py / compliance_engine.py).

Input:
  memory/semantic/prescriptions.json          (from prescriptor.py)
  10_swarm/coordination/swarm_coordination_<process>.json   (optional)
  10_swarm/organisms/<SLUG>/siop_internal.json              (optional)

Output:
  agentic_shield/decisions/shield_decisions.json
  agentic_shield/decisions/shield_decisions.jsonl   (audit trail, append-only)
  agentic_shield/state/policy_engine_state.json
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


CONFIDENCE_ESCALATE_BELOW = 0.70
CONFIDENCE_APPROVE_AT_OR_ABOVE = 0.85


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def append_jsonl(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(payload, ensure_ascii=False) + "\n")


def organism_to_slug(organism_name: str) -> str:
    """'Demand Planning Organism' -> 'DEMAND_PLANNING' (matches 10_swarm/organisms/<SLUG>)."""
    name = re.sub(r"\s*Organism\s*$", "", organism_name.strip())
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper()


class ArbitrationContext:
    """Loads swarm-level shield_arbitration and organism-level autonomy_design
    so the policy engine can match a prescription's action text against real
    governance boundaries instead of guessing.
    """

    def __init__(
        self,
        coordination_file: str | Path | None = None,
        client_root: str | Path | None = None,
        thresholds_file: str | Path | None = None,
    ):
        self.swarm_always_human: list[str] = []
        self.swarm_approval_required: list[str] = []
        self.swarm_autonomous_allowed: list[str] = []
        self.organism_profiles: dict[str, dict[str, Any]] = {}
        self.organism_thresholds: dict[str, dict[str, float]] = {}

        if thresholds_file:
            thresholds_payload = read_json(Path(thresholds_file), {})
            self.organism_thresholds = thresholds_payload.get("organisms", {})

        if coordination_file:
            coordination = read_json(Path(coordination_file), {})
            arbitration = coordination.get("shield_arbitration", {})
            self.swarm_always_human = [a.lower() for a in arbitration.get("always_human", [])]
            self.swarm_approval_required = [a.lower() for a in arbitration.get("approval_required", [])]
            self.swarm_autonomous_allowed = [a.lower() for a in arbitration.get("autonomous_allowed", [])]

        if client_root:
            organisms_dir = Path(client_root) / "10_swarm" / "organisms"
            if organisms_dir.exists():
                for organism_dir in sorted(organisms_dir.iterdir()):
                    profile_file = organism_dir / "siop_internal.json"
                    if not profile_file.exists():
                        continue
                    profile = read_json(profile_file, {})
                    if not profile:
                        continue
                    autonomy = profile.get("autonomy_design", {})
                    self.organism_profiles[organism_dir.name] = {
                        "always_human": [a.lower() for a in autonomy.get("always_human", [])],
                        "approval_required": [a.lower() for a in autonomy.get("approval_required", [])],
                        "autonomous_actions": [a.lower() for a in autonomy.get("autonomous_actions", [])],
                    }

    @property
    def loaded(self) -> bool:
        return bool(self.swarm_always_human or self.swarm_approval_required or self.organism_profiles)

    def thresholds_for(self, organism_slugs: list[str]) -> tuple[float, float, str]:
        """Resolve (escalate_below, approve_at_or_above, source) for this
        decision. If more than one affected organism has a calibrated
        threshold, the most cautious (highest escalate_below) wins - a
        multi-organism action is only as trustworthy as its strictest
        participant.
        """
        escalate_below = CONFIDENCE_ESCALATE_BELOW
        approve_at_or_above = CONFIDENCE_APPROVE_AT_OR_ABOVE
        source = "global_default"

        for slug in organism_slugs:
            calibrated = self.organism_thresholds.get(slug)
            if not calibrated:
                continue
            candidate_escalate = calibrated.get("escalate_below", CONFIDENCE_ESCALATE_BELOW)
            if candidate_escalate > escalate_below:
                escalate_below = candidate_escalate
                approve_at_or_above = calibrated.get(
                    "approve_at_or_above", CONFIDENCE_APPROVE_AT_OR_ABOVE
                )
                source = f"calibrated:{slug}"

        return escalate_below, approve_at_or_above, source

    def match_organism(self, action_text: str, organism_slugs: list[str]) -> tuple[str, str] | None:
        """Check organism-specific autonomy_design first (most specific signal)."""
        action_lower = action_text.lower()
        for slug in organism_slugs:
            profile = self.organism_profiles.get(slug)
            if not profile:
                continue
            for phrase in profile["always_human"]:
                if phrase in action_lower or action_lower in phrase:
                    return ("ESCALATE", f"organism:{slug} always_human:'{phrase}'")
            for phrase in profile["approval_required"]:
                if phrase in action_lower or action_lower in phrase:
                    return ("SANDBOX", f"organism:{slug} approval_required:'{phrase}'")
            for phrase in profile["autonomous_actions"]:
                if phrase in action_lower or action_lower in phrase:
                    return ("APPROVE", f"organism:{slug} autonomous_actions:'{phrase}'")
        return None

    def match_swarm(self, action_text: str) -> tuple[str, str] | None:
        """Fall back to process-wide shield_arbitration when no organism match."""
        action_lower = action_text.lower()
        for phrase in self.swarm_always_human:
            if phrase in action_lower or action_lower in phrase:
                return ("ESCALATE", f"swarm always_human:'{phrase}'")
        for phrase in self.swarm_approval_required:
            if phrase in action_lower or action_lower in phrase:
                return ("SANDBOX", f"swarm approval_required:'{phrase}'")
        for phrase in self.swarm_autonomous_allowed:
            if phrase in action_lower or action_lower in phrase:
                return ("APPROVE", f"swarm autonomous_allowed:'{phrase}'")
        return None


@dataclass
class ShieldDecision:
    decision_id: str
    created_at: str
    prescription_id: str
    pattern_name: str
    severity: str
    affected_organisms: list[str]
    proposed_action_type: str
    target_component: str
    confidence: float
    verdict: str
    rationale: str
    matched_rule: str
    requires_human: bool
    grounded: bool


class PolicyEngine:
    def __init__(
        self,
        memory_root: str | Path = "memory",
        state_root: str | Path = "agentic_shield/state",
        decisions_root: str | Path = "agentic_shield/decisions",
        coordination_file: str | Path | None = None,
        client_root: str | Path | None = None,
        thresholds_file: str | Path | None = None,
    ):
        self.memory_root = Path(memory_root)
        self.state_root = Path(state_root)
        self.decisions_root = Path(decisions_root)

        self.prescriptions_file = self.memory_root / "semantic" / "prescriptions.json"
        self.decisions_file = self.decisions_root / "shield_decisions.json"
        self.decisions_log = self.decisions_root / "shield_decisions.jsonl"
        self.state_file = self.state_root / "policy_engine_state.json"

        self.context = ArbitrationContext(coordination_file, client_root, thresholds_file)

    def action_text_for(self, prescription: dict[str, Any]) -> str:
        """Build the text the arbitration context matches against: the
        human-readable recommendation plus the structured shield_rule
        candidate's action, since either can carry the governance keyword.
        """
        parts = [
            prescription.get("recommendation", ""),
            prescription.get("proposed_action_type", ""),
            prescription.get("shield_rule_candidate", {}).get("action", ""),
        ]
        return " ".join(p for p in parts if p)

    def decide(self, prescription: dict[str, Any]) -> ShieldDecision:
        severity = prescription.get("severity", "LOW")
        confidence = float(prescription.get("confidence", 0.5))
        affected = prescription.get("affected_organisms", []) or []
        organism_slugs = [organism_to_slug(o) for o in affected]
        action_text = self.action_text_for(prescription)

        verdict = None
        rationale = ""
        matched_rule = ""
        grounded = False

        # 1. Organism-specific signal (most specific, wins)
        match = self.context.match_organism(action_text, organism_slugs)
        if match:
            verdict, matched_rule = match
            rationale = f"Matched organism-level autonomy_design: {matched_rule}"
            grounded = True

        # 2. Swarm-wide shield_arbitration
        if verdict is None:
            match = self.context.match_swarm(action_text)
            if match:
                verdict, matched_rule = match
                rationale = f"Matched swarm-level shield_arbitration: {matched_rule}"
                grounded = True

        # 3. Safety-net thresholds (no textual match, or no context loaded)
        if verdict is None:
            escalate_below, approve_at_or_above, threshold_source = self.context.thresholds_for(
                organism_slugs
            )
            if severity == "CRITICAL":
                verdict = "ESCALATE"
                rationale = "No governance match found; CRITICAL severity defaults to escalation."
            elif confidence < escalate_below:
                verdict = "ESCALATE"
                rationale = (
                    f"No governance match found; confidence {confidence} below escalate "
                    f"threshold {escalate_below} (source: {threshold_source})."
                )
            elif confidence >= approve_at_or_above and severity in ("LOW", "MEDIUM"):
                verdict = "SANDBOX"
                rationale = (
                    f"No explicit governance match found; confidence {confidence} clears "
                    f"{approve_at_or_above} (source: {threshold_source}) and severity {severity} is "
                    "non-critical, but absence of an explicit autonomous_allowed match means "
                    "this defaults to SANDBOX rather than a silent APPROVE."
                )
            else:
                verdict = "SANDBOX"
                rationale = "No governance match found; default-safe verdict is SANDBOX, never silent APPROVE."

        requires_human = verdict in ("ESCALATE", "REJECT")

        decision_payload = {
            "prescription_id": prescription.get("prescription_id", ""),
            "verdict": verdict,
        }

        return ShieldDecision(
            decision_id=f"SHIELD-{prescription.get('prescription_id', 'UNKNOWN')}",
            created_at=now(),
            prescription_id=prescription.get("prescription_id", ""),
            pattern_name=prescription.get("pattern_name", ""),
            severity=severity,
            affected_organisms=affected,
            proposed_action_type=prescription.get("proposed_action_type", ""),
            target_component=prescription.get("target_component", ""),
            confidence=confidence,
            verdict=verdict,
            rationale=rationale,
            matched_rule=matched_rule,
            requires_human=requires_human,
            grounded=grounded,
        )

    def run(self) -> dict[str, Any]:
        prescriptions_payload = read_json(self.prescriptions_file, {"prescriptions": []})
        prescriptions = prescriptions_payload.get("prescriptions", [])

        decisions: list[ShieldDecision] = []
        for prescription in prescriptions:
            decision = self.decide(prescription)
            decisions.append(decision)
            append_jsonl(self.decisions_log, asdict(decision))

        verdict_counts: dict[str, int] = {}
        for d in decisions:
            verdict_counts[d.verdict] = verdict_counts.get(d.verdict, 0) + 1

        payload = {
            "generated_at": now(),
            "decisions_count": len(decisions),
            "verdict_counts": verdict_counts,
            "context_loaded": self.context.loaded,
            "decisions": [asdict(d) for d in decisions],
        }
        write_json(self.decisions_file, payload)

        write_json(
            self.state_file,
            {
                "timestamp": now(),
                "module": "policy_engine",
                "status": "POLICY_ENGINE_ACTIVE",
                "decisions_count": len(decisions),
                "verdict_counts": verdict_counts,
                "context_loaded": self.context.loaded,
                "next_step": "Run threshold_engine.py and approval_engine.py for APPROVE/SANDBOX verdicts",
            },
        )

        return payload


def run_cli():
    parser = argparse.ArgumentParser(description="Agentic Zero - Agentic Shield Policy Engine")
    parser.add_argument("--memory-root", default="memory")
    parser.add_argument("--state-root", default="agentic_shield/state")
    parser.add_argument("--decisions-root", default="agentic_shield/decisions")
    parser.add_argument("--coordination-file", default="", help="Path to swarm_coordination_<process>.json")
    parser.add_argument("--client-root", default="", help="Client package root, for organism-level autonomy_design")
    parser.add_argument("--thresholds-file", default="", help="Path to thresholds.json from threshold_engine.py")
    parser.add_argument("--decide", action="store_true", help="Run a decision pass over current prescriptions")
    args = parser.parse_args()

    engine = PolicyEngine(
        memory_root=args.memory_root,
        state_root=args.state_root,
        decisions_root=args.decisions_root,
        coordination_file=args.coordination_file or None,
        client_root=args.client_root or None,
        thresholds_file=args.thresholds_file or None,
    )

    result = engine.run()

    print("\nAgentic Shield Policy Engine complete")
    print(f"Decisions made:  {result['decisions_count']}")
    print(f"Context loaded:  {result['context_loaded']}")
    print("Verdicts:")
    for verdict, count in result["verdict_counts"].items():
        print(f"  {verdict}: {count}")

    print("\nOutput:")
    print(f"  decisions:    {engine.decisions_file}")
    print(f"  decisions_log: {engine.decisions_log}")
    print(f"  state:        {engine.state_file}")


if __name__ == "__main__":
    run_cli()
