"""
AGENTIC ZERO - PIONEER TEAM
Guardian Adapter v1.0

Role:
  Adapt a customer Essential Package to the existing Guardian certification logic.

Why this exists:
  The existing guardian.py is valid and should not be replaced.
  It was designed for library packages generated by Builder + Packager.
  Essential delivery packages now live under:

    clients/{client}/{process}/essential_package/

  This adapter reads that Essential package and generates Guardian-compatible
  compliance outputs directly into:

    06_compliance/

Recommended location:
  pioneer_team/guardian/guardian_adapter.py

Input:
  --package-dir clients/{client}/{process}/essential_package

Output:
  06_compliance/
    guardian_result.json
    guardian_certificate.txt
    agentic_certificate.json

Next:
  auditor.py / delivery_gate.py

Mantra:
  Does this make it feel like a living enterprise?
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Optional


# ---------------------------------------------------------------------------
# MODELS
# ---------------------------------------------------------------------------


@dataclass
class CheckResult:
    name: str
    status: str  # PASS | WARN | FAIL
    score: float
    issues: list[str] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)


@dataclass
class AgenticCertificate:
    certificate_id: str
    issued_at: str
    process_id: str
    agent_name: str
    learning_ready: bool
    memory_ready: bool
    prescriptive_ready: bool
    self_improvement_ready: bool
    machine_compatible: bool
    score: float
    issues: list[str]
    recommendations: list[str]


@dataclass
class GuardianAdapterResult:
    process_id: str
    package_dir: str
    issued_at: str
    overall_status: str  # CERTIFIED | CONDITIONAL | REJECTED
    overall_score: float
    delivery_allowed: bool
    human_signoff_required: bool
    checks: list[CheckResult]
    agentic_certificate: AgenticCertificate
    remediation_plan: list[str]
    outputs: dict[str, str]
    next_step: str
    mantra: str = "Does this make it feel like a living enterprise?"


# ---------------------------------------------------------------------------
# UTILS
# ---------------------------------------------------------------------------


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _slug(value: str) -> str:
    value = (value or "process").lower().strip()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    return value.strip("_") or "process"


def read_json(
    path: str | Path, default: Optional[dict[str, Any]] = None
) -> dict[str, Any]:
    path = Path(path)
    if not path.exists():
        return default or {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def write_json(path: str | Path, payload: dict[str, Any]) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return path


def write_text(path: str | Path, text: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def exists(path: str | Path) -> bool:
    return Path(path).exists()


def pct(score: float) -> int:
    return int(round(score * 100))


# ---------------------------------------------------------------------------
# PACKAGE LOADER
# ---------------------------------------------------------------------------


def load_essential_package(package_dir: str | Path) -> dict[str, Any]:
    root = Path(package_dir)

    paths = {
        "functional": root / "01_functional_analysis" / "functional_analysis.json",
        "siop": root / "02_siop" / "siop_internal.json",
        "siop_validation": root / "02_siop" / "siop_validation.json",
        "blueprint": root / "03_blueprint" / "architect_blueprint.json",
        "agent_runtime": root / "04_agent" / "agent_runtime.py",
        "developer_manifest": root / "04_agent" / "developer_manifest.json",
        "sop": root / "05_delivery" / "sop.md",
        "integration_guide": root / "05_delivery" / "integration_guide.md",
        "escalation_policy": root / "05_delivery" / "escalation_policy.md",
        "client_summary": root / "05_delivery" / "client_executive_summary.md",
        "dashboard": root / "05_delivery" / "dashboard.html",
        "roi": root / "05_delivery" / "roi_calculator.html",
        "delivery_manifest": root / "delivery_manifest.json",
    }

    functional = read_json(paths["functional"])
    siop = read_json(paths["siop"])
    siop_validation = read_json(paths["siop_validation"])
    blueprint = read_json(paths["blueprint"])
    developer_manifest = read_json(paths["developer_manifest"])
    delivery_manifest = read_json(paths["delivery_manifest"])

    company = (
        blueprint.get("company")
        or siop.get("business_context", {}).get("company")
        or functional.get("business_context", {}).get("company")
        or delivery_manifest.get("company")
        or "Customer"
    )

    process_id = (
        blueprint.get("process_id")
        or siop.get("process_id")
        or siop.get("siop_id")
        or delivery_manifest.get("process_id")
        or "ESSENTIAL-PROCESS"
    )

    agent_name = (
        blueprint.get("agent_class_name")
        or developer_manifest.get("agent_class_name")
        or delivery_manifest.get("agent_class_name")
        or "EssentialAgent"
    )

    return {
        "root": root,
        "paths": paths,
        "functional": functional,
        "siop": siop,
        "siop_validation": siop_validation,
        "blueprint": blueprint,
        "developer_manifest": developer_manifest,
        "delivery_manifest": delivery_manifest,
        "company": company,
        "process_id": process_id,
        "agent_name": agent_name,
    }


# ---------------------------------------------------------------------------
# CHECKS
# ---------------------------------------------------------------------------


def check_artifact_completeness(pkg: dict[str, Any]) -> CheckResult:
    required = [
        "functional",
        "siop",
        "siop_validation",
        "blueprint",
        "agent_runtime",
        "sop",
        "integration_guide",
        "escalation_policy",
        "client_summary",
        "dashboard",
        "roi",
        "delivery_manifest",
    ]

    missing = [k for k in required if not pkg["paths"][k].exists()]
    score = max(0.0, 1.0 - (len(missing) * 0.08))

    status = "PASS" if not missing else ("WARN" if score >= 0.70 else "FAIL")

    return CheckResult(
        name="artifact_completeness",
        status=status,
        score=round(score, 2),
        issues=[f"Missing artifact: {m}" for m in missing],
        recommendations=["Generate missing artifacts before delivery"]
        if missing
        else [],
    )


def check_eu_ai_act(pkg: dict[str, Any]) -> CheckResult:
    text = json.dumps(
        {
            "functional": pkg["functional"],
            "siop": pkg["siop"],
            "blueprint": pkg["blueprint"],
        },
        ensure_ascii=False,
    ).lower()

    prohibited_terms = [
        "social scoring",
        "mass surveillance",
        "subliminal manipulation",
        "exploit vulnerabilities",
    ]

    high_risk_terms = [
        "biometric",
        "law enforcement",
        "medical",
        "pharma",
        "defense",
        "creditworthiness",
        "worker evaluation",
        "recruitment",
        "critical infrastructure",
    ]

    issues = []
    recommendations = []

    if any(t in text for t in prohibited_terms):
        return CheckResult(
            name="eu_ai_act",
            status="FAIL",
            score=0.0,
            issues=["Possible prohibited AI use case detected"],
            recommendations=["Human legal review required before continuing"],
        )

    risk_level = "minimal"
    if any(t in text for t in high_risk_terms):
        risk_level = "high"
        issues.append("High-risk indicators detected")
        recommendations.extend(
            [
                "Document EU AI Act Art.9 risk management system",
                "Document Art.10 data governance",
                "Document Art.11 technical documentation",
                "Document Art.12 logging",
                "Document Art.14 human oversight",
            ]
        )

    blueprint = pkg["blueprint"]
    shield = blueprint.get("shield_requirements", [])
    audit_ok = any("audit" in str(s).lower() for s in shield) or "audit" in text
    human_ok = (
        any("human" in str(s).lower() for s in shield) or "human oversight" in text
    )

    if not audit_ok:
        issues.append("EU AI Act logging/audit trail not explicit")
        recommendations.append("Add explicit Art.12 audit trail requirement")

    if not human_ok:
        issues.append("EU AI Act human oversight not explicit")
        recommendations.append("Add explicit Art.14 human oversight checkpoint")

    if risk_level == "high":
        score = 0.75 if audit_ok and human_ok else 0.62
        status = "WARN"
    else:
        score = 0.92 if audit_ok and human_ok else 0.78
        status = "PASS" if score >= 0.85 else "WARN"

    return CheckResult(
        name="eu_ai_act",
        status=status,
        score=round(score, 2),
        issues=issues,
        recommendations=recommendations,
    )


def check_gdpr(pkg: dict[str, Any]) -> CheckResult:
    text = json.dumps(
        {
            "functional": pkg["functional"],
            "siop": pkg["siop"],
            "blueprint": pkg["blueprint"],
        },
        ensure_ascii=False,
    ).lower()

    personal_terms = [
        "customer",
        "email",
        "name",
        "address",
        "employee",
        "contact",
        "phone",
        "personal",
        "id",
    ]

    personal_data = any(t in text for t in personal_terms)
    issues = []
    recommendations = []

    if personal_data:
        issues.append("Personal or contact data likely involved")
        recommendations.extend(
            [
                "Define lawful basis for processing",
                "Confirm data minimization",
                "Confirm retention policy",
                "Ensure audit trail for personal data access",
            ]
        )

    score = 0.82 if personal_data else 0.95
    status = "WARN" if personal_data else "PASS"

    return CheckResult(
        name="gdpr",
        status=status,
        score=score,
        issues=issues,
        recommendations=recommendations,
    )


def check_iso_42001(pkg: dict[str, Any]) -> CheckResult:
    blueprint = pkg["blueprint"]
    siop = pkg["siop"]

    issues = []
    recommendations = []

    has_risk = bool(siop.get("compliance") or blueprint.get("compliance_frameworks"))
    has_monitoring = bool(blueprint.get("kpis") or siop.get("acceptance_criteria"))
    has_improvement = bool(
        blueprint.get("learning_hooks") or siop.get("learning_hooks")
    )

    if not has_risk:
        issues.append("AI risk/compliance context not explicit")
    if not has_monitoring:
        issues.append("AI performance monitoring not explicit")
    if not has_improvement:
        issues.append("Continual improvement / learning hooks missing")

    recommendations.extend(
        [
            "Map AI risks to ISO/IEC 42001 planning controls",
            "Keep KPI monitoring evidence",
            "Register improvement actions through The Machine",
        ]
    )

    score = 1.0
    if not has_risk:
        score -= 0.18
    if not has_monitoring:
        score -= 0.18
    if not has_improvement:
        score -= 0.18

    status = "PASS" if score >= 0.85 else ("WARN" if score >= 0.65 else "FAIL")

    return CheckResult(
        name="iso_42001",
        status=status,
        score=round(score, 2),
        issues=issues,
        recommendations=recommendations if issues else [],
    )


def check_nist_ai_rmf(pkg: dict[str, Any]) -> CheckResult:
    blueprint = pkg["blueprint"]
    siop = pkg["siop"]

    govern = bool(blueprint.get("shield_requirements") or siop.get("compliance"))
    map_ = bool(
        siop.get("business_context") or pkg["functional"].get("business_context")
    )
    measure = bool(blueprint.get("kpis") or siop.get("acceptance_criteria"))
    manage = bool(blueprint.get("escalations") or siop.get("autonomy_design"))

    checks = {
        "govern": govern,
        "map": map_,
        "measure": measure,
        "manage": manage,
    }

    missing = [k for k, v in checks.items() if not v]
    score = sum(1 for v in checks.values() if v) / 4

    return CheckResult(
        name="nist_ai_rmf",
        status="PASS" if score >= 0.85 else ("WARN" if score >= 0.60 else "FAIL"),
        score=round(score, 2),
        issues=[f"NIST function incomplete: {m}" for m in missing],
        recommendations=["Complete NIST AI RMF Govern/Map/Measure/Manage evidence"]
        if missing
        else [],
    )


def check_agentic_shield(pkg: dict[str, Any]) -> CheckResult:
    blueprint = pkg["blueprint"]
    shield = " ".join(str(x) for x in blueprint.get("shield_requirements", [])).lower()

    required = {
        "identity": ["identity", "access"],
        "thresholds": ["threshold"],
        "audit": ["audit", "log"],
        "escalation": ["escalation"],
        "fail_safe": ["fail", "safe", "rollback"],
        "human_accountability": ["human", "accountability", "oversight"],
    }

    missing = []
    for key, terms in required.items():
        if not any(t in shield for t in terms):
            missing.append(key)

    score = max(0.0, 1.0 - len(missing) * 0.12)
    status = "PASS" if not missing else ("WARN" if score >= 0.70 else "FAIL")

    return CheckResult(
        name="agentic_shield",
        status=status,
        score=round(score, 2),
        issues=[f"Missing Shield control: {m}" for m in missing],
        recommendations=["Add missing Shield controls to ArchitectBlueprint"]
        if missing
        else [],
    )


def check_living_enterprise(pkg: dict[str, Any]) -> CheckResult:
    hooks = (
        pkg["blueprint"].get("learning_hooks")
        or pkg["siop"].get("learning_hooks")
        or {}
    )

    required = [
        "observation_points",
        "failure_patterns",
        "kpi_deviation_signals",
        "feedback_targets",
        "improvement_loop",
    ]

    missing = [k for k in required if not hooks.get(k)]
    score = max(0.0, 1.0 - len(missing) * 0.16)
    status = "PASS" if not missing else ("WARN" if score >= 0.60 else "FAIL")

    return CheckResult(
        name="living_enterprise",
        status=status,
        score=round(score, 2),
        issues=[f"Missing learning hook: {m}" for m in missing],
        recommendations=[
            "Complete learning hooks so The Machine can learn from this agent"
        ]
        if missing
        else [],
    )


def run_all_checks(pkg: dict[str, Any]) -> list[CheckResult]:
    return [
        check_artifact_completeness(pkg),
        check_eu_ai_act(pkg),
        check_gdpr(pkg),
        check_iso_42001(pkg),
        check_nist_ai_rmf(pkg),
        check_agentic_shield(pkg),
        check_living_enterprise(pkg),
    ]


# ---------------------------------------------------------------------------
# AGENTIC CERTIFICATE
# ---------------------------------------------------------------------------


def build_agentic_certificate(
    pkg: dict[str, Any], checks: list[CheckResult]
) -> AgenticCertificate:
    hooks = (
        pkg["blueprint"].get("learning_hooks")
        or pkg["siop"].get("learning_hooks")
        or {}
    )

    learning_ready = bool(hooks)
    memory_ready = bool(
        hooks.get("observation_points") or hooks.get("failure_patterns")
    )
    prescriptive_ready = bool(
        hooks.get("improvement_loop") or hooks.get("feedback_targets")
    )
    self_improvement_ready = bool(
        hooks.get("kpi_deviation_signals") and hooks.get("feedback_targets")
    )
    machine_compatible = all(
        [
            learning_ready,
            memory_ready,
            prescriptive_ready,
            self_improvement_ready,
        ]
    )

    score_items = [
        learning_ready,
        memory_ready,
        prescriptive_ready,
        self_improvement_ready,
        machine_compatible,
    ]
    score = sum(1 for x in score_items if x) / len(score_items)

    issues = []
    recommendations = []

    if not learning_ready:
        issues.append("Learning hooks missing")
    if not memory_ready:
        issues.append("Memory observation points missing")
    if not prescriptive_ready:
        issues.append("Prescriptive feedback loop missing")
    if not self_improvement_ready:
        issues.append("Self-improvement signals incomplete")
    if not machine_compatible:
        recommendations.append("Complete hooks before connecting to The Machine")

    return AgenticCertificate(
        certificate_id=f"AZ-AGENTIC-{pkg['process_id']}-{datetime.now().strftime('%Y%m%d')}",
        issued_at=_now(),
        process_id=pkg["process_id"],
        agent_name=pkg["agent_name"],
        learning_ready=learning_ready,
        memory_ready=memory_ready,
        prescriptive_ready=prescriptive_ready,
        self_improvement_ready=self_improvement_ready,
        machine_compatible=machine_compatible,
        score=round(score, 2),
        issues=issues,
        recommendations=recommendations,
    )


# ---------------------------------------------------------------------------
# DECISION
# ---------------------------------------------------------------------------


def decide_status(
    checks: list[CheckResult],
) -> tuple[str, float, bool, bool, list[str]]:
    scores = [c.score for c in checks]
    overall_score = round(sum(scores) / len(scores), 2) if scores else 0.0

    fails = [c for c in checks if c.status == "FAIL"]
    warns = [c for c in checks if c.status == "WARN"]

    remediation = []
    for c in checks:
        remediation.extend([f"{c.name}: {i}" for i in c.issues])
        remediation.extend([f"{c.name}: {r}" for r in c.recommendations])

    if fails:
        return "REJECTED", overall_score, False, True, remediation

    if warns or overall_score < 0.88:
        return "CONDITIONAL", overall_score, True, True, remediation

    return "CERTIFIED", overall_score, True, False, remediation


# ---------------------------------------------------------------------------
# OUTPUT WRITERS
# ---------------------------------------------------------------------------


def render_certificate_text(result: GuardianAdapterResult) -> str:
    valid_until = (datetime.now(timezone.utc) + timedelta(days=365)).date().isoformat()

    lines = [
        "AGENTIC ZERO - GUARDIAN CERTIFICATE",
        "=" * 42,
        f"Process ID:       {result.process_id}",
        f"Agent:            {result.agentic_certificate.agent_name}",
        f"Issued at:        {result.issued_at}",
        f"Valid until:      {valid_until}",
        f"Overall status:   {result.overall_status}",
        f"Overall score:    {pct(result.overall_score)}%",
        f"Delivery allowed: {result.delivery_allowed}",
        f"Human signoff:    {result.human_signoff_required}",
        "",
        "CHECK SUMMARY",
        "-" * 42,
    ]

    for check in result.checks:
        lines.extend(
            [
                f"{check.name}: {check.status} ({pct(check.score)}%)",
                *[f"  - {i}" for i in check.issues[:5]],
            ]
        )

    lines.extend(
        [
            "",
            "AGENTIC CERTIFICATE",
            "-" * 42,
            f"Learning ready:          {result.agentic_certificate.learning_ready}",
            f"Memory ready:            {result.agentic_certificate.memory_ready}",
            f"Prescriptive ready:      {result.agentic_certificate.prescriptive_ready}",
            f"Self-improvement ready:  {result.agentic_certificate.self_improvement_ready}",
            f"Machine compatible:      {result.agentic_certificate.machine_compatible}",
            f"Agentic score:           {pct(result.agentic_certificate.score)}%",
            "",
            "REMEDIATION PLAN",
            "-" * 42,
        ]
    )

    if result.remediation_plan:
        lines.extend([f"- {r}" for r in result.remediation_plan[:20]])
    else:
        lines.append("- No remediation required")

    lines.extend(
        [
            "",
            "MANTRA",
            "-" * 42,
            result.mantra,
        ]
    )

    return "\n".join(lines)


def save_outputs(
    pkg: dict[str, Any], result: GuardianAdapterResult
) -> GuardianAdapterResult:
    compliance_dir = pkg["root"] / "06_compliance"
    compliance_dir.mkdir(parents=True, exist_ok=True)

    guardian_result_path = compliance_dir / "guardian_result.json"
    guardian_certificate_path = compliance_dir / "guardian_certificate.txt"
    agentic_certificate_path = compliance_dir / "agentic_certificate.json"

    write_json(guardian_result_path, asdict(result))
    write_text(guardian_certificate_path, render_certificate_text(result))
    write_json(agentic_certificate_path, asdict(result.agentic_certificate))

    result.outputs = {
        "guardian_result_json": str(guardian_result_path),
        "guardian_certificate_txt": str(guardian_certificate_path),
        "agentic_certificate_json": str(agentic_certificate_path),
    }

    write_json(guardian_result_path, asdict(result))
    return result


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------


def certify_essential_package(package_dir: str | Path) -> GuardianAdapterResult:
    pkg = load_essential_package(package_dir)
    checks = run_all_checks(pkg)
    agentic_cert = build_agentic_certificate(pkg, checks)

    (
        overall_status,
        overall_score,
        delivery_allowed,
        human_signoff_required,
        remediation,
    ) = decide_status(checks)

    if not agentic_cert.machine_compatible:
        if overall_status == "CERTIFIED":
            overall_status = "CONDITIONAL"
        human_signoff_required = True
        remediation.append(
            "agentic_certificate: complete Machine compatibility before autonomous learning activation"
        )

    result = GuardianAdapterResult(
        process_id=pkg["process_id"],
        package_dir=str(pkg["root"]),
        issued_at=_now(),
        overall_status=overall_status,
        overall_score=overall_score,
        delivery_allowed=delivery_allowed,
        human_signoff_required=human_signoff_required,
        checks=checks,
        agentic_certificate=agentic_cert,
        remediation_plan=remediation,
        outputs={},
        next_step="Run auditor.py / delivery_gate.py",
    )

    return save_outputs(pkg, result)


def run_cli(package_dir: str):
    result = certify_essential_package(package_dir)

    print("\nGuardian Adapter complete")
    print(f"Status: {result.overall_status}")
    print(f"Score:  {pct(result.overall_score)}%")
    print(f"Delivery allowed: {result.delivery_allowed}")
    print(f"Human signoff:    {result.human_signoff_required}")
    print("\nOutput:")
    for k, v in result.outputs.items():
        print(f"  {k}: {v}")
    print(f"\nNext: {result.next_step}")

    if result.remediation_plan:
        print("\nTop remediation:")
        for item in result.remediation_plan[:8]:
            print(f"  - {item}")

    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Agentic Zero - Guardian Adapter")
    parser.add_argument(
        "--package-dir", required=True, help="Path to customer essential_package folder"
    )
    args = parser.parse_args()
    run_cli(args.package_dir)
